services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: multi-agent-rag-app 
    container_name: multi-agent-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    command: streamlit run app/main.py --server.port=8501 --server.enableCORS=false
